name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  check:
    name: 🔎 Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test --watchAll=false

  build:
    name: 👷🏼‍♂️ Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Install Dependencies
        run: yarn build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: leda-web
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
