name: Continuous Deployment (Production)
on:
  tag:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test --watchAll=false

      - name: Build
        run: yarn build

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: leda-web
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
