name: Deploy to development environment on DO
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Format code
        run: yarn format --write .

      - name: Check format
        run: yarn format:check

      - name: Run tests
        run: yarn test --watchAll=false

      - name: Build
        run: yarn build

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: leda-marketplace
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
